<?php

/**
 * @file
 * Provides a refferal management for admin for Drupal commerce
 */

/**
 * Implementation of hook_init().
 */
function extlink_overlay_init() {
  $path = drupal_get_path('module', 'extlink_overlay');
  drupal_add_js($path.'/extlink_overlay.js');
  drupal_add_js(array('extlink_overlay' => array(
    'extOverlayPopUp'     => variable_get('extlink_overlay_popup', 0),)), 'setting'
  );
  drupal_add_css($path.'/extlink_overlay.css');
}

/**
 * Implementation of hook_form_alter().
 */
function extlink_overlay_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'extlink_admin_settings') {
     $form['extlink_overlay_popup'] = array(
      '#type' => 'checkbox',
      '#title' => t('Open external links in a pop-up'),
      '#return_value' => '_blank',
      '#default_value' => variable_get('extlink_overlay_popup', 0),
      '#description' => t('Should all external links be opened in a pop-up?'),
   );
  }
}
